# Generated by Django 2.1 on 2019-07-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_notification',
            name='title',
            field=models.CharField(default='SOMESTRING', max_length=100),
        ),
    ]
