# Generated by Django 2.1 on 2019-07-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_send_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_notification',
            name='notification_concern',
            field=models.CharField(blank=True, choices=[('Requested Document', 'Requested Document'), ('Complaint', 'Complaint')], max_length=100),
        ),
    ]
