# Generated by Django 2.1.7 on 2019-07-22 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_description', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('Resolved', 'Resolved'), ('Unresolved', 'Unresolved'), ('Pending', 'Pending')], max_length=100)),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('complaint_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requested_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_document', models.CharField(choices=[('Business Permit', 'Business Permit'), ('Indigency', 'Indigency'), ('Barangay Clearance', 'Barangay Clearance')], max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending')], max_length=100)),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('requested_document_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_description', models.TextField(max_length=255)),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('suggestion_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
