# Generated by Django 2.1.7 on 2019-07-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='status',
            new_name='status_complaint',
        ),
    ]
