# Generated by Django 2.1 on 2019-07-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_auto_20190723_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requested_document',
            name='status_of_document',
            field=models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending'), ('Did not received', 'Did not received')], max_length=100),
        ),
    ]
