# Generated by Django 2.1.7 on 2019-06-28 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_notif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('notif_concern', models.CharField(choices=[('Requested Document', 'Requested Document'), ('Complaint', 'Complaint')], max_length=100)),
            ],
        ),
    ]
