# Generated by Django 2.1.7 on 2019-06-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_send_notif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='send_notif',
            old_name='notif_concern',
            new_name='notification_concern',
        ),
    ]
