# Generated by Django 2.1.7 on 2019-06-30 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190628_1601'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Send_notif',
            new_name='Send_notification',
        ),
    ]
