# Generated by Django 2.1.7 on 2019-07-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190630_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Send_notification',
        ),
    ]
